const fs = require('fs');
const path = require('path');

const allStatesAndUTs = [
  // 28 States
  { id: 'state-1', category: 'states', titleEn: 'Andhra Pradesh', titleHi: 'आंध्र प्रदेश', titleUr: 'آندھرا پردیش', capitalEn: 'Amaravati', capitalHi: 'अमरावती', capitalUr: 'امراوتی', detailEn: 'State in southern coastal India known for Kuchipudi dance and Tirupati temple.', detailHi: 'कुचिपुड़ी नृत्य और तिरुपति बालाजी मंदिर के लिए प्रसिद्ध दक्षिण भारतीय राज्य।', detailUr: 'کوچی پوڑی رقص اور تروپتی مندر کے لیے مشہور جنوبی ریاست۔', imageUrl: '🏛️', order: 1 },
  { id: 'state-2', category: 'states', titleEn: 'Arunachal Pradesh', titleHi: 'अरुणाचल प्रदेश', titleUr: 'اروناچل پردیش', capitalEn: 'Itanagar', capitalHi: 'ईटानगर', capitalUr: 'ایٹانگر', detailEn: 'Land of Dawn-lit Mountains in Northeast India, first to see the sunrise.', detailHi: 'पूर्वोत्तर भारत में उगते सूरज की भूमि और प्राकृतिक सौंदर्य से भरपूर राज्य।', detailUr: 'طلوع آفتاب کی سرزمین، شمال مشرقی بھارت کی خوبصورت ریاست۔', imageUrl: '🌄', order: 2 },
  { id: 'state-3', category: 'states', titleEn: 'Assam', titleHi: 'असम', titleUr: 'آسام', capitalEn: 'Dispur', capitalHi: 'दिसपुर', capitalUr: 'دسپور', detailEn: 'Known for Assam tea, one-horned rhinos in Kaziranga, and the Brahmaputra River.', detailHi: 'असम चाय, काजीरंगा के एक सींग वाले गैंडे और ब्रह्मपुत्र नदी के लिए प्रसिद्ध।', detailUr: 'آسام کی چائے، کاظیرنگا کے گینڈے اور برہمپترا ندی کے لیے مشہور۔', imageUrl: '🦏', order: 3 },
  { id: 'state-4', category: 'states', titleEn: 'Bihar', titleHi: 'बिहार', titleUr: 'بہار', capitalEn: 'Patna', capitalHi: 'पटना', capitalUr: 'پٹنہ', detailEn: 'Ancient seat of learning (Nalanda), birthplace of Buddhism & Jainism, and land of Aryabhata.', detailHi: 'नालंदा का ऐतिहासिक ज्ञान केंद्र, बौद्ध व जैन धर्म की पावन भूमि और आर्यभट्ट का प्रदेश।', detailUr: 'نالندہ کی تاریخی درسگاہ، بدھ مت و جین مت کی جنم بھومی اور عظیم تاریخ۔', imageUrl: '🏛️', order: 4 },
  { id: 'state-5', category: 'states', titleEn: 'Chhattisgarh', titleHi: 'छत्तीसगढ़', titleUr: 'چھتیس گڑھ', capitalEn: 'Raipur', capitalHi: 'रायपुर', capitalUr: 'رائے پور', detailEn: 'Known as the Rice Bowl of Central India with rich mineral resources and tribal culture.', detailHi: 'मध्य भारत का धान का कटोरा, समृद्ध खनिज संपदा और जनजातीय संस्कृति का केंद्र।', detailUr: 'چاول کا کٹورا کہلانے والی معدنیات سے مالامال ریاست۔', imageUrl: '🌾', order: 5 },
  { id: 'state-6', category: 'states', titleEn: 'Goa', titleHi: 'गोवा', titleUr: 'گوا', capitalEn: 'Panaji', capitalHi: 'पणजी', capitalUr: 'پنجی', detailEn: 'India\'s smallest state by area, famous for beautiful beaches and Portuguese heritage.', detailHi: 'क्षेत्रफल में भारत का सबसे छोटा राज्य, खूबसूरत समुद्र तटों और पुर्तगाली धरोहर के लिए विख्यात।', detailUr: 'رقبے کے لحاظ سے بھارت کی سب سے چھوٹی اور خوبصورت ساحلی ریاست۔', imageUrl: '🏖️', order: 6 },
  { id: 'state-7', category: 'states', titleEn: 'Gujarat', titleHi: 'गुजरात', titleUr: 'گجرات', capitalEn: 'Gandhinagar', capitalHi: 'गांधीनगर', capitalUr: 'گاندھی نگر', detailEn: 'Birthplace of Mahatma Gandhi & Sardar Patel; home to Asiatic lions in Gir Forest.', detailHi: 'महात्मा गांधी और सरदार पटेल की जन्मभूमि; गिर राष्ट्रीय उद्यान के एशियाई शेरों का घर।', detailUr: 'مہاتما گاندھی کی جنم بھومی اور گر جنگل کے ایشیائی ببر شیروں کا مسکن۔', imageUrl: '🦁', order: 7 },
  { id: 'state-8', category: 'states', titleEn: 'Haryana', titleHi: 'हरियाणा', titleUr: 'ہریانہ', capitalEn: 'Chandigarh', capitalHi: 'चंडीगढ़', capitalUr: 'چندی گڑھ', detailEn: 'Agricultural hub of North India and powerhouse of Olympic athletes and sports champions.', detailHi: 'उत्तर भारत का प्रमुख कृषि केंद्र और ओलंपिक पदक विजेता खिलाड़ियों की भूमि।', detailUr: 'کھیلوں کے چیمپئنز اور زرعی ترقی کے لیے مشہور ریاست۔', imageUrl: '🏅', order: 8 },
  { id: 'state-9', category: 'states', titleEn: 'Himachal Pradesh', titleHi: 'हिमाचल प्रदेश', titleUr: 'ہماچل پردیش', capitalEn: 'Shimla', capitalHi: 'शिमला', capitalUr: 'شملہ', detailEn: 'Land of Gods in the Himalayas, famed for apple orchards, snow-capped peaks and valleys.', detailHi: 'हिमालय की गोद में देवभूमि, सेब के बगीचों, बर्फीली चोटियों और घाटियों के लिए प्रसिद्ध।', detailUr: 'دیو بھومی، سیب کے باغات اور برف پوش پہاڑوں کی حسین وادی۔', imageUrl: '🏔️', order: 9 },
  { id: 'state-10', category: 'states', titleEn: 'Jharkhand', titleHi: 'झारखंड', titleUr: 'جھارکھنڈ', capitalEn: 'Ranchi', capitalHi: 'राँची', capitalUr: 'رانچی', detailEn: 'Land of Forests rich in mineral wealth (coal, iron), Betla National Park, and waterfalls.', detailHi: 'खनिज संपदा (कोयला, लोहा), जलप्रपातों और बेतला राष्ट्रीय उद्यान से समृद्ध वनांचल राज्य।', detailUr: 'معدنیات کے ذخائر، آبشاروں اور گھنے جنگلات کی ریاست۔', imageUrl: '⛏️', order: 10 },
  { id: 'state-11', category: 'states', titleEn: 'Karnataka', titleHi: 'कर्नाटक', titleUr: 'کرناٹک', capitalEn: 'Bengaluru', capitalHi: 'बेंगलुरु', capitalUr: 'بنگلورو', detailEn: 'Silicon Valley of India (Bengaluru), historic ruins of Hampi, and rich Carnatic music.', detailHi: 'भारत की सिलिकॉन वैली (बेंगलुरु), हम्पी के ऐतिहासिक स्मारक और कर्नाटक संगीत का केंद्र।', detailUr: 'بھارت کی سلیکان ویلی اور ہمپی کے تاریخی کھنڈرات کا مرکز۔', imageUrl: '💻', order: 11 },
  { id: 'state-12', category: 'states', titleEn: 'Kerala', titleHi: 'केरल', titleUr: 'کیرالہ', capitalEn: 'Thiruvananthapuram', capitalHi: 'तिरुवनंतपुरम', capitalUr: 'تھرواننت پورم', detailEn: 'God\'s Own Country with highest literacy rate in India, serene backwaters, and Ayurvedic heritage.', detailHi: 'ईश्वर का अपना देश, भारत में सर्वाधिक साक्षरता दर, शांत बैकवाटर्स और आयुर्वेद की भूमि।', detailUr: 'سب سے زیادہ شرح خواندگی اور خوبصورت جھیلوں کی وادی۔', imageUrl: '🌴', order: 12 },
  { id: 'state-13', category: 'states', titleEn: 'Madhya Pradesh', titleHi: 'मध्य प्रदेश', titleUr: 'مدھیہ پردیش', capitalEn: 'Bhopal', capitalHi: 'भोपाल', capitalUr: 'بھوپال', detailEn: 'Heart of India with the largest tiger population (Kanha, Bandhavgarh) and Khajuraho temples.', detailHi: 'भारत का दिल, सर्वाधिक बाघों वाला राज्य, कान्हा-बांधवगढ़ राष्ट्रीय उद्यान और खजुराहो स्मारक।', detailUr: 'بھارت کا دل اور سب سے زیادہ ٹائیگرز والی ریاست۔', imageUrl: '🐅', order: 13 },
  { id: 'state-14', category: 'states', titleEn: 'Maharashtra', titleHi: 'महाराष्ट्र', titleUr: 'مہاراشٹر', capitalEn: 'Mumbai', capitalHi: 'मुंबई', capitalUr: 'ممبئی', detailEn: 'Financial capital of India (Mumbai), historical forts of Chhatrapati Shivaji Maharaj and Ajanta caves.', detailHi: 'भारत की आर्थिक राजधानी (मुंबई), छत्रपति शिवाजी महाराज के ऐतिहासिक किले और अजंता-एलोरा गुफाएं।', detailUr: 'بھارت کا معاشی مرکز (ممبئی) اور تاریخی قلعوں کی سرزمین۔', imageUrl: '🏙️', order: 14 },
  { id: 'state-15', category: 'states', titleEn: 'Manipur', titleHi: 'मणिपुर', titleUr: 'منی پور', capitalEn: 'Imphal', capitalHi: 'इंफाल', capitalUr: 'امپھال', detailEn: 'Jeweled Land famous for Loktak floating lake, Sangai deer, and martial arts.', detailHi: 'लोकटक झील, संगाई हिरण और पारंपरिक मार्शल आर्ट के लिए प्रसिद्ध पूर्वोत्तर का नगीना।', detailUr: 'تیرتی ہوئی لوکتک جھیل اور خوبصورت وادیوں کی ریاست۔', imageUrl: '🦌', order: 15 },
  { id: 'state-16', category: 'states', titleEn: 'Meghalaya', titleHi: 'मेघालय', titleUr: 'میگھالیہ', capitalEn: 'Shillong', capitalHi: 'शिलांग', capitalUr: 'شیلانگ', detailEn: 'Abode of Clouds, home to Mawsynram (wettest place on Earth) and Living Root Bridges.', detailHi: 'बादलों का घर, दुनिया का सबसे नम स्थान मौसिनराम और जीवित जड़ों के प्राकृतिक पुल।', detailUr: 'بادلوں کا گھر، دنیا میں سب سے زیادہ بارش کا مقام۔', imageUrl: '🌧️', order: 16 },
  { id: 'state-17', category: 'states', titleEn: 'Mizoram', titleHi: 'मिज़ोरम', titleUr: 'میزورم', capitalEn: 'Aizawl', capitalHi: 'आइज़ोल', capitalUr: 'آئزول', detailEn: 'Land of the Hill People known for lush rolling bamboo hills and Cheraw bamboo dance.', detailHi: 'बांस के घने जंगलों, चेराव लोकनृत्य और शांत पहाड़ियों वाला पूर्वोत्तर राज्य।', detailUr: 'بانس کے رقص اور سرسبز پہاڑوں کی پرامن ریاست۔', imageUrl: '🎋', order: 17 },
  { id: 'state-18', category: 'states', titleEn: 'Nagaland', titleHi: 'नागालैंड', titleUr: 'ناگالینڈ', capitalEn: 'Kohima', capitalHi: 'कोहिमा', capitalUr: 'کوہیما', detailEn: 'Land of Festivals famous for the grand Hornbill Festival and rich tribal traditions.', detailHi: 'त्योहारों की भूमि, प्रसिद्ध हॉर्नबिल महोत्सव और गौरवशाली नागा संस्कृति।', detailUr: 'ہارن بل فیسٹیول اور روایتی قبائلی ثقافت کی سرزمین۔', imageUrl: '🦅', order: 18 },
  { id: 'state-19', category: 'states', titleEn: 'Odisha', titleHi: 'ओडिशा', titleUr: 'اوڈیشہ', capitalEn: 'Bhubaneswar', capitalHi: 'भुवनेश्वर', capitalUr: 'بھونیشور', detailEn: 'Land of Jagannath Puri temple, Konark Sun Temple, Chilika Lake, and Odissi classical dance.', detailHi: 'जगन्नाथ पुरी धाम, कोणार्क सूर्य मंदिर, चिल्का झील और ओडिसी शास्त्रीय नृत्य की भूमि।', detailUr: 'پوری جگن ناتھ مندر، کونارک اور چیلکا جھیل کا تاریخی خطہ۔', imageUrl: '🛕', order: 19 },
  { id: 'state-20', category: 'states', titleEn: 'Punjab', titleHi: 'पंजाब', titleUr: 'پنجاب', capitalEn: 'Chandigarh', capitalHi: 'चंडीगढ़', capitalUr: 'چندی گڑھ', detailEn: 'Land of Five Rivers, Golden Temple (Amritsar), vibrant Bhangra dance, and agricultural prosperity.', detailHi: 'पाँच नदियों की भूमि, श्री हरमंदिर साहिब (स्वर्ण मंदिर), भांगड़ा नृत्य और अन्नदाता प्रदेश।', detailUr: 'پانچ دریاؤں کی دھرتی اور گولڈن ٹیمپل کی مقدس سرزمین۔', imageUrl: '🌾', order: 20 },
  { id: 'state-21', category: 'states', titleEn: 'Rajasthan', titleHi: 'राजस्थान', titleUr: 'راجستھان', capitalEn: 'Jaipur', capitalHi: 'जयपुर', capitalUr: 'جے پور', detailEn: 'Largest Indian state by area, land of royal palaces, Thar Desert, and vibrant folk traditions.', detailHi: 'क्षेत्रफल में भारत का सबसे बड़ा राज्य, राजाओं के महलों, थार मरुस्थल और लोक संस्कृति की भूमि।', detailUr: 'رقبے کے لحاظ سے سب سے بڑی ریاست، شاہی محلات اور صحرائے تھر۔', imageUrl: '🏰', order: 21 },
  { id: 'state-22', category: 'states', titleEn: 'Sikkim', titleHi: 'सिक्किम', titleUr: 'سکم', capitalEn: 'Gangtok', capitalHi: 'गंगटोक', capitalUr: 'گنگٹوک', detailEn: 'First 100% organic state of the world, home to Mount Kangchenjunga (3rd highest peak).', detailHi: 'दुनिया का पहला 100% जैविक राज्य और कंचनजंगा पर्वत शिखर की गोद में बसा राज्य।', detailUr: 'دنیا کی پہلی نامیاتی ریاست اور کنچن جنگا پہاڑ کا گھر۔', imageUrl: '🏔️', order: 22 },
  { id: 'state-23', category: 'states', titleEn: 'Tamil Nadu', titleHi: 'तमिलनाडु', titleUr: 'تمل ناڈو', capitalEn: 'Chennai', capitalHi: 'चेन्नई', capitalUr: 'چنئی', detailEn: 'Dravidian heritage, ancient temples (Meenakshi Amman), Bharatanatyam dance, and automobile hub.', detailHi: 'द्रविड़ संस्कृति, मीनाक्षी मंदिर, भरतनाट्यम शास्त्रीय नृत्य और ऑटोमोबाइल उद्योग का प्रमुख केंद्र।', detailUr: 'قدیم دراوڑی تہذیب، برہتاناطیم رقص اور تاریخی مندروں کی ریاست۔', imageUrl: '🛕', order: 23 },
  { id: 'state-24', category: 'states', titleEn: 'Telangana', titleHi: 'तेलंगाना', titleUr: 'تلنگانہ', capitalEn: 'Hyderabad', capitalHi: 'हैदराबाद', capitalUr: 'حیدرآباد', detailEn: 'Charminar and Golconda Fort in Hyderabad, leading IT hub, pharma capital, and Kakatiya architecture.', detailHi: 'हैदराबाद का चारमीनार, गोलकोंडा किला, प्रमुख आईटी और फार्मास्युटिकल हब।', detailUr: 'چارمینار، تاریخی حیدرآباد اور آئی ٹی کا بڑا مرکز۔', imageUrl: '🏛️', order: 24 },
  { id: 'state-25', category: 'states', titleEn: 'Tripura', titleHi: 'त्रिपुरा', titleUr: 'تریپورہ', capitalEn: 'Agartala', capitalHi: 'अगरतला', capitalUr: 'اگرتلہ', detailEn: 'Known for Ujjayanta Palace, Neermahal water palace, and rich bamboo handicrafts.', detailHi: 'उज्जयंत पैलेस, नीरमहल जल महल और उत्कृष्ट बांस हस्तशिल्प के लिए प्रसिद्ध।', detailUr: 'اجینتا پیلس اور بانس کی شاندار دستکاری۔', imageUrl: '🏰', order: 25 },
  { id: 'state-26', category: 'states', titleEn: 'Uttar Pradesh', titleHi: 'उत्तर प्रदेश', titleUr: 'اتر پردیش', capitalEn: 'Lucknow', capitalHi: 'लखनऊ', capitalUr: 'لکھنؤ', detailEn: 'Most populous Indian state; home to Taj Mahal (Agra), Varanasi ghats, and Sangam in Prayagraj.', detailHi: 'भारत का सबसे अधिक जनसंख्या वाला राज्य; ताजमहल (आगरा), काशी-वाराणसी और प्रयागराज संगम।', detailUr: 'سب سے زیادہ آبادی والی ریاست؛ تاج محل اور وارانسی کی تاریخی سرزمین۔', imageUrl: '🕌', order: 26 },
  { id: 'state-27', category: 'states', titleEn: 'Uttarakhand', titleHi: 'उत्तराखंड', titleUr: 'اتراکھنڈ', capitalEn: 'Dehradun', capitalHi: 'देहरादून', capitalUr: 'دہرادون', detailEn: 'Devbhoomi (Land of Gods), origin of holy rivers Ganga & Yamuna, Jim Corbett Tiger Reserve.', detailHi: 'देवभूमि, गंगा और यमुना नदियों का उद्गम स्थल और जिम कॉर्बेट नेशनल पार्क।', detailUr: 'دیو بھومی، دریائے گنگا و جمنا کا منبع اور قدرتی خوبصورتی۔', imageUrl: '🏔️', order: 27 },
  { id: 'state-28', category: 'states', titleEn: 'West Bengal', titleHi: 'पश्चिम बंगाल', titleUr: 'مغربی بنگال', capitalEn: 'Kolkata', capitalHi: 'कोलकाता', capitalUr: 'کولکاتا', detailEn: 'Land of Rabindranath Tagore, Sundarbans mangrove tiger habitat, Victoria Memorial and Durga Puja.', detailHi: 'रवींद्रनाथ टैगोर की कर्मभूमि, सुंदरबन मैंग्रोव और दुर्गा पूजा का सांस्कृतिक केंद्र।', detailUr: 'ٹیگور کی سرزمین، سندر بن ٹائیگرز اور کولکاتا کی ثقافت۔', imageUrl: '🐯', order: 28 },

  // 8 Union Territories
  { id: 'ut-1', category: 'states', titleEn: 'Delhi (NCT)', titleHi: 'दिल्ली (राष्ट्रीय राजधानी क्षेत्र)', titleUr: 'دہلی (قومی دارالحکومت)', capitalEn: 'New Delhi', capitalHi: 'नई दिल्ली', capitalUr: 'نئی دہلی', detailEn: 'Capital city of India; home to Red Fort, India Gate, Rashtrapati Bhavan and Qutub Minar.', detailHi: 'भारत की राजधानी; लाल किला, इंडिया गेट, राष्ट्रपति भवन और कुतुब मीनार का ऐतिहासिक नगर।', detailUr: 'بھارت کا دارالحکومت؛ لال قلعہ، انڈیا گیٹ اور راشٹرپتی بھون۔', imageUrl: '🏛️', order: 29 },
  { id: 'ut-2', category: 'states', titleEn: 'Jammu and Kashmir', titleHi: 'जम्मू और कश्मीर', titleUr: 'جموں و کشمیر', capitalEn: 'Srinagar (Summer) / Jammu (Winter)', capitalHi: 'श्रीनगर (ग्रीष्म) / जम्मू (शीत)', capitalUr: 'سری نگر (گرما) / جموں (سرما)', detailEn: 'Paradise on Earth, famed for Dal Lake Shikaras, Chinar trees, and Gulmarg snow sports.', detailHi: 'धरती का स्वर्ग, डल झील के शिकारे, चिनार के पेड़ और गुलमर्ग के बर्फ के पहाड़।', detailUr: 'زمین کی جنت، ڈل جھیل اور خوبصورت وادی کشمیر۔', imageUrl: '🏔️', order: 30 },
  { id: 'ut-3', category: 'states', titleEn: 'Ladakh', titleHi: 'लद्दाख', titleUr: 'لداخ', capitalEn: 'Leh', capitalHi: 'लेह', capitalUr: 'لیہہ', detailEn: 'High altitude desert known for Pangong Tso lake, Buddhist monasteries and Khardung La pass.', detailHi: 'ऊंचे हिमालय का ठंडा मरुस्थल, पैंगोंग झील, बौद्ध मठ और खारदुंग ला दर्रा।', detailUr: 'بلند ترین سرد صحرا، پینگونگ جھیل اور تاریخی خانقاہیں۔', imageUrl: '🏞️', order: 31 },
  { id: 'ut-4', category: 'states', titleEn: 'Chandigarh', titleHi: 'चंडीगढ़', titleUr: 'چندی گڑھ', capitalEn: 'Chandigarh', capitalHi: 'चंडीगढ़', capitalUr: 'چندی گڑھ', detailEn: 'Beautiful planned modern city designed by Le Corbusier, joint capital of Punjab & Haryana.', detailHi: 'ली कार्बुजिए द्वारा डिजाइन किया गया सुंदर नियोजित शहर, पंजाब और हरियाणा की संयुक्त राजधानी।', detailUr: 'منظم اور خوبصورت شہر، پنجاب اور ہریانہ کا مشترکہ دارالحکومت۔', imageUrl: '🌳', order: 32 },
  { id: 'ut-5', category: 'states', titleEn: 'Puducherry', titleHi: 'पुदुचेरी', titleUr: 'پڈوچیری', capitalEn: 'Puducherry', capitalHi: 'पुदुचेरी', capitalUr: 'پڈوچیری', detailEn: 'Former French colony known for French quarters, Promenade beach, and Sri Aurobindo Ashram.', detailHi: 'पूर्व फ्रांसीसी उपनिवेश, फ्रांसीसी वास्तुकला, समुद्र तट और श्री अरविंद आश्रम।', detailUr: 'فرانسیسی کالونی کا تاریخی ورثہ اور خوبصورت ساحل۔', imageUrl: '🏖️', order: 33 },
  { id: 'ut-6', category: 'states', titleEn: 'Andaman & Nicobar Islands', titleHi: 'अंडमान और निकोबार द्वीप समूह', titleUr: 'انڈمان و نکوبار جزائر', capitalEn: 'Port Blair', capitalHi: 'पोर्ट ब्लेयर', capitalUr: 'پورٹ بلیئر', detailEn: 'Archipelago of 572 islands in the Bay of Bengal, Cellular Jail (Kala Pani) and coral reefs.', detailHi: 'बंगाल की खाड़ी में 572 द्वीपों का समूह, ऐतिहासिक सेल्यूलर जेल (काला पानी) और मूंगा चट्टानें।', detailUr: 'خلیج بنگال کے خوبصورت جزائر اور تاریخی سیلولر جیل۔', imageUrl: '🏝️', order: 34 },
  { id: 'ut-7', category: 'states', titleEn: 'Dadra & Nagar Haveli and Daman & Diu', titleHi: 'दादरा एवं नगर हवेली और दमन एवं दीव', titleUr: 'دادرا و نگر حویلی اور دمن و دیو', capitalEn: 'Daman', capitalHi: 'दमन', capitalUr: 'دمن', detailEn: 'Western coastal union territory with Portuguese forts, beaches, and rich industrial growth.', detailHi: 'पुर्तगाली किलों, समुद्र तटों और समृद्ध औद्योगिक विकास वाला पश्चिमी केंद्र शासित प्रदेश।', detailUr: 'پرتگالی قلعوں اور ساحلوں کا خوبصورت خطہ۔', imageUrl: '🏰', order: 35 },
  { id: 'ut-8', category: 'states', titleEn: 'Lakshadweep', titleHi: 'लक्षद्वीप', titleUr: 'لکشادیپ', capitalEn: 'Kavaratti', capitalHi: 'कवरत्ती', capitalUr: 'کورتی', detailEn: 'Tropical coral island chain in the Arabian Sea with crystal clear turquoise lagoons.', detailHi: 'अरब सागर में मूंगा द्वीपों का खूबसूरत समूह और नीले पानी के लैगून।', detailUr: 'بحر عرب میں مرجان کے خوبصورت جزائر۔', imageUrl: '🌊', order: 36 }
];

const nationalSymbols = [
  { id: 'sym-1', category: 'symbols', titleEn: 'National Animal: Royal Bengal Tiger', titleHi: 'राष्ट्रीय पशु: रॉयल बंगाल टाइगर (बाघ)', titleUr: 'قومی جانور: رائل بنگال ٹائیگر (شیر)', tenure: 'Symbol of Strength & Grace', detailEn: 'The Royal Bengal Tiger represents unmatched strength, agility, grace and supreme power.', detailHi: 'रॉयल बंगाल टाइगर अदम्य शक्ति, चपलता, गरिमा और प्राकृतिक संतुलन का प्रतीक है।', detailUr: 'رائل بنگال ٹائیگر طاقت، چستی اور وقار کی شاندار علامت ہے۔', imageUrl: '🐅', order: 1 },
  { id: 'sym-2', category: 'symbols', titleEn: 'National Bird: Indian Peacock', titleHi: 'राष्ट्रीय पक्षी: भारतीय मोर', titleUr: 'قومی پرندہ: مور (مور)', tenure: 'Symbol of Beauty & Joy', detailEn: 'The Peacock (Pavo cristatus) is celebrated for its breathtaking feathers and majestic rain dance.', detailHi: 'भारतीय मोर अपनी मनमोहक सुंदरता, रंग-बिरंगे पंखों और वर्षा नृत्य के लिए प्रसिद्ध है।', detailUr: 'مور اپنی خوبصورت رنگت اور شاندار پنکھ پھیلانے کے لیے مشہور ہے۔', imageUrl: '🦚', order: 2 },
  { id: 'sym-3', category: 'symbols', titleEn: 'National Flower: Lotus', titleHi: 'राष्ट्रीय फूल: कमल', titleUr: 'قومی پھول: کنول (کمل)', tenure: 'Symbol of Purity & Wisdom', detailEn: 'The sacred Lotus (Nelumbo nucifera) blooms purely above muddy water, symbolizing spiritual purity.', detailHi: 'पवित्र कमल का फूल कीचड़ में खिलकर भी निर्मलता, ज्ञान और दिव्यता का संदेश देता है।', detailUr: 'کنول کا پھول پاکیزگی اور حکمت کی لازوال علامت ہے۔', imageUrl: '🪷', order: 3 },
  { id: 'sym-4', category: 'symbols', titleEn: 'National Emblem: Lion Capital of Ashoka', titleHi: 'राष्ट्रीय प्रतीक: अशोक स्तंभ (चार सिंह)', titleUr: 'قومی نشان: اشوک ستون (چار شیر)', tenure: 'Motto: Satyameva Jayate', detailEn: 'Adapted from the Ashoka Pillar at Sarnath, featuring four lions standing back to back and "Satyameva Jayate" (Truth Alone Triumphs).', detailHi: 'सारनाथ के अशोक स्तंभ से लिया गया, चार सिंहों और "सत्यमेव जयते" (सत्य की ही जीत होती है) से सुशोभित।', detailUr: 'سارناتھ کے اشوک ستون سے ماخوذ، "ستیہ میو جیتے" (سچائی کی فتح) کا نعرہ۔', imageUrl: '🏛️', order: 4 },
  { id: 'sym-5', category: 'symbols', titleEn: 'National Flag: Tiranga (Tricolour)', titleHi: 'राष्ट्रीय ध्वज: तिरंगा', titleUr: 'قومی پرچم: ترنگا', tenure: 'Saffron, White, Green & Chakra', detailEn: 'Saffron for courage and sacrifice, White for peace and truth, Green for fertility and growth, and the 24-spoke Navy Blue Ashoka Chakra for righteousness.', detailHi: 'केसरिया (साहस व बलिदान), सफेद (शांति व सत्य), हरा (समृद्धि) और 24 तीलियों वाला नीला अशोक चक्र (धर्म व न्याय)।', detailUr: 'زعفرانی (قربانی)، سفید (امن)، سبز (خوشحالی) اور 24 تیلیوں والا اشوک چکر۔', imageUrl: '🇮🇳', order: 5 },
  { id: 'sym-6', category: 'symbols', titleEn: 'National Anthem: Jana Gana Mana', titleHi: 'राष्ट्रगान: जन गण मन', titleUr: 'قومی ترانہ: جن گن من', tenure: 'Composed by Rabindranath Tagore', detailEn: 'Composed by Nobel laureate Rabindranath Tagore, adopted on 24 January 1950, playing time is 52 seconds.', detailHi: 'नोबेल पुरस्कार विजेता रवींद्रनाथ टैगोर द्वारा रचित, 24 जनवरी 1950 को स्वीकृत, गायन समय 52 सेकंड।', detailUr: 'رابندر ناتھ ٹیگور کا لکھا ہوا قومی ترانہ، مدت 52 سیکنڈ۔', imageUrl: '🎵', order: 6 },
  { id: 'sym-7', category: 'symbols', titleEn: 'National Song: Vande Mataram', titleHi: 'राष्ट्रगीत: वन्दे मातरम्', titleUr: 'قومی گیت: وندے ماترم', tenure: 'Composed by Bankim Chandra Chattopadhyay', detailEn: 'Written in Sanskrit by Bankim Chandra Chattopadhyay in his novel Anandamath; historic anthem of Indian freedom movement.', detailHi: 'बंकिम चंद्र चट्टोपाध्याय द्वारा उनके उपन्यास आनंदमठ में रचित; स्वतंत्रता संग्राम का अमर प्रेरणा गीत।', detailUr: 'بنکم چندر چٹرجی کا تحریر کردہ تاریخی آزادی کا گیت۔', imageUrl: '📜', order: 7 },
  { id: 'sym-8', category: 'symbols', titleEn: 'National Tree: Banyan Tree (Bargad)', titleHi: 'राष्ट्रीय वृक्ष: बरगद (वटवृक्ष)', titleUr: 'قومی درخت: برگد کا درخت', tenure: 'Symbol of Immortality & Protection', detailEn: 'The Banyan tree (Ficus benghalensis) represents eternal life, extensive shelter and deep unshakeable roots.', detailHi: 'विशाल बरगद का पेड़ अमरता, छाया, संरक्षण और भारतीय संस्कृति की गहरी जड़ों का प्रतीक है।', detailUr: 'برگد کا عظیم درخت بقا اور تحفظ کی علامت ہے۔', imageUrl: '🌳', order: 8 },
  { id: 'sym-9', category: 'symbols', titleEn: 'National Fruit: Mango (Aam)', titleHi: 'राष्ट्रीय फल: आम (फलों का राजा)', titleUr: 'قومی پھل: آم (پھلوں کا بادشاہ)', tenure: 'King of Fruits', detailEn: 'The delicious Mango (Mangifera indica) symbolizes abundance, sweetness and the warmth of tropical India.', detailHi: 'स्वादिष्ट आम फलों का राजा है और भारत की समृद्ध प्रकृति, मिठास व प्रचुरता का प्रतीक है।', detailUr: 'آم پھلوں کا بادشاہ، بھارت کی قدرتی مٹھاس کی پہچان۔', imageUrl: '🥭', order: 9 },
  { id: 'sym-10', category: 'symbols', titleEn: 'National River: Ganga', titleHi: 'राष्ट्रीय नदी: गंगा', titleUr: 'قومی دریا: دریائے گنگا', tenure: 'Lifeline of Millions', detailEn: 'The longest river flowing entirely in India (2,525 km), originating from Gangotri glacier in the Himalayas.', detailHi: 'भारत की सबसे पवित्र और 2525 किमी लंबी जीवनदायिनी नदी, जो हिमालय के गंगोत्री से निकलती है।', detailUr: 'بھارت کا سب سے طویل اور اہم دریا (2525 کلومیٹر)۔', imageUrl: '🌊', order: 10 },
  { id: 'sym-11', category: 'symbols', titleEn: 'National Aquatic Animal: Gangetic Dolphin', titleHi: 'राष्ट्रीय जलीय जीव: गंगा डॉल्फिन', titleUr: 'قومی آبی جانور: گنگا ڈولفن', tenure: 'Symbol of Clean Rivers', detailEn: 'The endangered South Asian River Dolphin lives in freshwater Ganga and Brahmaputra river systems.', detailHi: 'गंगा और ब्रह्मपुत्र की मीठे पानी की डॉल्फिन जो शुद्ध जलीय पारिस्थितिकी की पहचान है।', detailUr: 'گنگا اور برہمپترا کی نایاب اور خوبصورت ڈولفن۔', imageUrl: '🐬', order: 11 },
  { id: 'sym-12', category: 'symbols', titleEn: 'National Currency: Indian Rupee (₹)', titleHi: 'राष्ट्रीय मुद्रा: भारतीय रुपया (₹)', titleUr: 'قومی کرنسی: بھارتی روپیہ (₹)', tenure: 'Symbol designed by D. Udaya Kumar', detailEn: 'The official currency symbol ₹ blends the Devanagari "र" (Ra) and Roman "R", adopted in 2010.', detailHi: 'आधिकारिक मुद्रा प्रतीक ₹ देवनागरी "र" और रोमन "R" का सुंदर सम्मिश्रण है, जिसे 2010 में अपनाया गया।', detailUr: 'بھارتی کرنسی کا سرکاری نشان ₹ جو دیوناگری اور انگریزی کا امتزاج ہے۔', imageUrl: '₹', order: 12 }
];

async function updateAll() {
  const dbPath = path.join(__dirname, '../data/db.json');
  const db = JSON.parse(fs.readFileSync(dbPath, 'utf-8'));

  // Remove existing states and symbols to replace with complete sets
  const otherItems = (db.gkItems || []).filter(i => i.category !== 'states' && i.category !== 'symbols');

  db.gkItems = [...allStatesAndUTs, ...otherItems, ...nationalSymbols];

  const jsonStr = JSON.stringify(db, null, 2);
  fs.writeFileSync(dbPath, jsonStr, 'utf-8');
  console.log('Updated data/db.json! Total GK items:', db.gkItems.length);

  const tsContent = `import { AppDatabase } from '../src/types.ts';\n\nexport const initialDatabase: AppDatabase = ${jsonStr};\n`;
  fs.writeFileSync(path.join(__dirname, '../server/initialData.ts'), tsContent, 'utf-8');
  console.log('Updated server/initialData.ts! Total GK items:', db.gkItems.length);
}

updateAll();
